# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
