# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tingweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tingweb.models.food_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tingweb.models.food_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tingweb.models.food_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tingweb.models.restaurant_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='image',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Food'),
        ),
        migrations.AddField(
            model_name='drinkimage',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Drink'),
        ),
        migrations.AddField(
            model_name='dishimage',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Dish'),
        ),
    ]
