# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingadmin', '0001_initial'),
        ('tingweb', '0002_auto_20190430_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingadmin.RestaurantCategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Restaurant')),
            ],
        ),
    ]
