# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0003_auto_20190606_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='purpose',
            field=models.IntegerField(default=2),
        ),
    ]
