# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingadmin', '0001_initial'),
        ('tingweb', '0004_auto_20190430_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantLicenceKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingadmin.TingLicenceKey')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Restaurant')),
            ],
        ),
    ]
