# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0004_restaurant_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tingweb.Branch'),
            preserve_default=False,
        ),
    ]
