# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import tingweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0005_promotion_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='poster_image',
            field=models.ImageField(default=None, upload_to=tingweb.models.promotion_image_path),
            preserve_default=False,
        ),
    ]
