# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0006_auto_20190502_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(default='Ting.com', max_length=200),
        ),
    ]
