# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0006_promotion_poster_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='supplement_max_quantity',
            new_name='supplement_min_quantity',
        ),
    ]
