# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0007_restaurant_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantconfig',
            name='book_with_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='booking_advance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='waiter_see_all_orders',
            field=models.BooleanField(default=False),
        ),
    ]
