# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-08 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0008_auto_20190607_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tingweb.FoodCategory'),
        ),
    ]
