# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import tingweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0009_auto_20190508_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='image',
            field=models.ImageField(upload_to=tingweb.models.administrator_image_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(upload_to=tingweb.models.restaurant_logo_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=tingweb.models.user_image_path),
        ),
    ]
