# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0010_auto_20190509_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantconfig',
            name='assign_table_to_waiter',
            field=models.BooleanField(default=True),
        ),
    ]
