# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0011_restaurantconfig_assign_table_to_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
