# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0012_auto_20190709_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='specials',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
