# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0012_administrator_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
