# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0013_restaurant_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
