# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0013_branch_specials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
