# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0014_auto_20190716_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreview',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Branch'),
            preserve_default=False,
        ),
    ]
