# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0015_adminpermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpermission',
            old_name='admin',
            new_name='administrator',
        ),
    ]
