# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0016_auto_20190514_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpermission',
            name='administrator',
        ),
        migrations.AddField(
            model_name='adminpermission',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tingweb.Administrator'),
            preserve_default=False,
        ),
    ]
