# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0016_userrestaurant_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='booking_cancelation_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='booking_cancelation_refund_percent',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='booking_payement_mode',
            field=models.IntegerField(default=3),
        ),
    ]
