# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0017_auto_20190514_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermission',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Administrator'),
        ),
        migrations.AlterField(
            model_name='restaurantconfig',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Restaurant'),
        ),
    ]
