# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0017_auto_20190720_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantconfig',
            name='days_before_reservation',
            field=models.IntegerField(default=3),
        ),
    ]
