# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0018_auto_20190514_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='drink',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
