# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0018_restaurantconfig_days_before_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tingweb.RestaurantTable'),
        ),
    ]
