# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0020_resetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Administrator')),
            ],
        ),
        migrations.RemoveField(
            model_name='resetpassword',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
