# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0021_auto_20190528_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratorresetpassword',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
