# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-24 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0021_auto_20190723_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantconfig',
            name='can_take_away',
            field=models.BooleanField(default=True),
        ),
    ]
