# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingadmin', '0002_restaurantcategory_image'),
        ('tingweb', '0024_branch_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tingadmin.RestaurantCategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tingadmin.RestaurantCategory'),
        ),
    ]
