# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-03 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0025_auto_20191228_0944'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch',
            managers=[
                ('random', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dish',
            managers=[
                ('random', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='drink',
            managers=[
                ('random', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='food',
            managers=[
                ('random', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='menu',
            managers=[
                ('random', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='promotion',
            managers=[
                ('random', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
                ('random', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='for_all_branches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='for_all_branches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='services',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
