# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-03 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0026_auto_20200103_0946'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='dish',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='drink',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='food',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='menu',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='promotion',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
            ],
        ),
    ]
