# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-06 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0027_auto_20200103_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='road',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
