# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0029_branch_restaurant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
