# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-13 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0030_auto_20200210_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tingweb.Administrator'),
        ),
    ]
