# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-18 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0031_restauranttable_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='uuid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
