# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-21 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0032_auto_20200218_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='placement',
        ),
        migrations.AddField(
            model_name='bill',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tingweb.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tingweb.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placement',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tingweb.Bill'),
        ),
    ]
