# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0033_auto_20200221_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
