# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0036_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tips',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
