# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0038_bill_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='extras_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='billextra',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Bill'),
        ),
    ]
