# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-26 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tingweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0041_auto_20200321_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tingweb.Placement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.User')),
            ],
        ),
        migrations.CreateModel(
            name='MomentMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=100)),
                ('media', models.FileField(upload_to=tingweb.models.moment_file_path)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tingweb.Moment')),
            ],
        ),
    ]
