# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingweb', '0042_moment_momentmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
