# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-28 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import tingadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('tingadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcategory',
            name='image',
            field=models.ImageField(default='', upload_to=tingadmin.models.restaurants_category_image_path),
            preserve_default=False,
        ),
    ]
